import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.SUPABASE_URL!
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

// Client for user operations (uses anon key)
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Admin client for server-side operations (uses service role key)
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
})

// Database types (will be generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string | null
          name: string | null
          avatar: string | null
          google_id: string | null
          solana_public_key: string | null
          provider: string | null
          role: string
          last_login: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email?: string | null
          name?: string | null
          avatar?: string | null
          google_id?: string | null
          solana_public_key?: string | null
          provider?: string | null
          role?: string
          last_login?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          name?: string | null
          avatar?: string | null
          google_id?: string | null
          solana_public_key?: string | null
          provider?: string | null
          role?: string
          last_login?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ai_prediction_logs: {
        Row: {
          id: number
          wager_id: string
          title: string
          confidence_pct: number | null
          model_provider: string
          model_name: string
          model_version: string | null
          created_utc: string
          server_received_utc: string
          app_env: string
          cid0g: string | null
          integrity_sha256: string | null
          created_at: string
          user_id: string | null
        }
        Insert: {
          id?: number
          wager_id: string
          title: string
          confidence_pct?: number | null
          model_provider: string
          model_name: string
          model_version?: string | null
          created_utc: string
          server_received_utc: string
          app_env: string
          cid0g?: string | null
          integrity_sha256?: string | null
          created_at?: string
          user_id?: string | null
        }
        Update: {
          id?: number
          wager_id?: string
          title?: string
          confidence_pct?: number | null
          model_provider?: string
          model_name?: string
          model_version?: string | null
          created_utc?: string
          server_received_utc?: string
          app_env?: string
          cid0g?: string | null
          integrity_sha256?: string | null
          created_at?: string
          user_id?: string | null
        }
      }
    }
  }
}
